### ISSUE TITLE
HW material Issue 

### ISSUE THREAD

**Issue by romillzoo7** [aaronksaunders/hu1#1]
URL
.Template 
('FirstController', function ($scope, MyDataService) {

```
$scope.itemsList = [];

/**
 * called when user click button in ui to refresh the list
 * 
 * this function is exposed to view
 */
$scope.getAllItemsBtnClicked = function () {
    populateList();
}

/**
 * calls the service to get the data to populate the list
 * 
 * this function is NOT exposed to view
 */
function populateList() {
    MyDataService.getAllItems().then(function (_data) {
        $scope.itemsList = _data;
    });
}

// To initialize the view, call populateList when controller
// starts
populateList();
```

});
 Body 
.controller('FirstController', function ($scope, MyDataService) {

```
$scope.itemsList = [];

/**
 * called when user click button in ui to refresh the list
 * 
 * this function is exposed to view
 */
$scope.getAllItemsBtnClicked = function () {
    populateList();
}

/**
 * calls the service to get the data to populate the list
 * 
 * this function is NOT exposed to view
 */
function populateList() {
    MyDataService.getAllItems().then(function (_data) {
        $scope.itemsList = _data;
    });
}

// To initialize the view, call populateList when controller
// starts
populateList();
```

Do Not fully understand will READ and do better and more hence forth,

<!DOCTYPE html>
<html ng-app="firstApp">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, 
                   user-scalable=no, width=device-width">
    <link href="http://code.ionicframework.com/1.0.0/css/ionic.min.css" rel="stylesheet">
    <script src="http://code.ionicframework.com/1.0.0/js/ionic.bundle.js"></script>
    
    <script src="app.js"></script>
</head>

<body ng-controller="FirstController">
    
    <ion-header-bar class="bar-royal">
        <h1 class="title">Home Page Title</h1>
    </ion-header-bar>
    
    <ion-content class="padding">
        <ion-list>
            
            <ion-item class="item-divider">List of Objects</ion-item>
            
            <ion-item ng-repeat="item in itemsList track by $index">
                {{$index}} - {{item.name}} - {{item.room}}
                <p>Item = {{item | json}} $index= {{$index}}</p>
            </ion-item>
            <ion-item class="item-divider">Actions</ion-item>
        </ion-list>
        <ion-item>
            <Button class="button" ng-click="getOneItemBtnClicked()">
                Get Item By ID
            </Button>&nbsp;
            <Button class="button" ng-click="getAllItemsBtnClicked()">
                Reset List
            </Button>
        </ion-item>
    </ion-content>
</body>
</html>
app.js

// this will be the javascript file to hold all of the code for my first app
// create the angular module
angular.module('firstApp', ['ionic'])
    .service('MyDataService', function ($q) {
        // Setup data
        var itemsList = [];
        itemsList.push({
            "name": "big screen TV",
            "room": "Basement"
        });
        itemsList.push({
            "name": "Xbox One",
            "room": "Basement"
        });
        itemsList.push({
            "name": "Ice Maker",
            "room": "Kitchen"
        });
        itemsList.push({
            "name": "China Cabinet",
            "room": "Dining Room"
        });
        itemsList.push({
            "name": "Formal Dinning Set",
            "room": "Dining Room"
        });

```
    // these are functions exposed to public
    return {
        /**
         * returns all of the data
         */
        getAllItems: function () {
            var deferred = $q.defer();
            setTimeout(function () {
                deferred.resolve(itemsList);
            }, 500);
            return deferred.promise;
        },
        /**
         * Gets item by specific id
         * @param   {Number}  _itemId index in the array
         * @returns {Promise}
         */
        getItemById: function (_itemId) {
            var deferred = $q.defer();
            setTimeout(function () {
                if (_itemId > itemsList.length || (_itemId < 0)) {
                    deferred.reject("Invalid Object Id");
                } else {
                    deferred.resolve(itemsList[_itemId]);
                }
            }, 1000);
            return deferred.promise;
        }
    }

})
```

.controller('FirstController', function ($scope, MyDataService) {
    /\* BODY OF CONTROLLER - ADD CODE HERE */

```
$scope.itemsList = [];
```

// 
/**
- called when user click button to get one item based
- on the items id
- 
- this function is exposed to view
  */
  $scope.getOneItemBtnClicked = function () {
  var objectId = prompt("Please enter object ID", "");
  if (objectId != null) {
      // call service to get data
      MyDataService.getItemById(objectId).then(function (_data) {
          // promise resolved with data
          $scope.itemsList = [_data];
      }, function error(_error) {
          // error trying to get data
          alert("Error accessing data " + _error);
      });
  }
  }
  
  /**
  - called when user click button in ui to refresh the list
  - 
  - this function is exposed to view
    */
    $scope.getAllItemsBtnClicked = function () {
    populateList();
    }
  
  /**
  - calls the service to get the data to populate the list
  - 
  - this function is NOT exposed to view
    */
    function populateList() {
    MyDataService.getAllItems().then(function (_data) {
        $scope.itemsList = _data;
    });
    }
  
  // To initialize the view, call populateList when controller
  // starts
  populateList();

});

**Comment by aaronksaunders** [comment]
this is not where you post homework issues
